trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployWithHelm
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  # - task: AzurePowerShell@5
  #   inputs:
  #     azureSubscription: 'Az'  # Specify your Azure subscription
  #     ScriptType: 'InlineScript'
  #     Inline: |
  #       Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser
  #       Import-Module Az

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Az'
      KeyVaultName: 'envchec'
      SecretsFilter: '*'                          
      RunAsPreJob: false

  - powershell: |
      # $secrets = Get-AzKeyVaultSecret -VaultName "envchec" -AsPlainText
      Set-Content -Path $(System.DefaultWorkingDirectory)/my-chart/values.yaml -Value "secrets:`r`n  keyVaultSecret1: '$($secrets.Secret1)'`r`n  keyVaultSecret2: '$($secrets.Secret2)'"
    displayName: 'Update Helm Chart Values'

  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'kubecluster'
      command: 'install'
      chartType: 'FilePath'
      chartPath: '$(System.DefaultWorkingDirectory)/my-chart'
      releaseName: 'env'
