trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployWithHelm
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Az'  # Replace with your Azure subscription name
      KeyVaultName: 'envchec'            # Replace with your Key Vault name
      SecretsFilter: '*'                          # Retrieve all secrets
      RunAsPreJob: false

  - script: |
      echo "env:" > $(System.DefaultWorkingDirectory)/values.yaml
      echo "  key1: $(AppName)" >> $(System.DefaultWorkingDirectory)/values.yaml
      echo "  key2: $(PortNumber)" >> $(System.DefaultWorkingDirectory)/values.yaml
      cat $(System.DefaultWorkingDirectory)/values.yaml
    displayName: 'Print values.yaml'


  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'kubecluster'
      command: 'install'
      chartType: 'FilePath'
      chartPath: '$(System.DefaultWorkingDirectory)/my-chart'
      releaseName: 'env'
      overrideValues: |
        key1=$(AppName)
        key2=$(PortNumber)
