trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployWithHelm
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Az'
      KeyVaultName: 'envchec'
      SecretsFilter: '*'                          
      RunAsPreJob: false

  - script: |
      echo "env:" > $(System.DefaultWorkingDirectory)/values.yaml
      echo "  key1: $(AppName)" >> $(System.DefaultWorkingDirectory)/values.yaml
      echo "  key2: $(PortNumber)" >> $(System.DefaultWorkingDirectory)/values.yaml
    displayName: 'Create values.yaml file'

  # - task: HelmDeploy@0
  #   inputs:
  #     connectionType: 'Kubernetes Service Connection'
  #     kubernetesServiceConnection: 'kubecluster'
  #     command: 'install'
  #     chartType: 'FilePath'
  #     chartPath: '$(System.DefaultWorkingDirectory)/my-chart'
  #     releaseName: 'env'


  - task: HelmDeploy@0
    inputs:
      # azureSubscriptionForACR: '3a8533e4-924b-4304-9ac3-b7d16f9ceb7b'
      # azureResourceGroupForACR: 'Feroz-RG'
      # azureContainerRegistry: 'acuraz'
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'kubecluster'
      command: 'install'
      chartType: 'FilePath'
      chartPath: '$(System.DefaultWorkingDirectory)/my-chart'
      releaseName: 'env'
      overrideValues: |
        key1=$(AppName)
        key2=$(PortNumber)