trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployWithHelm
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Az'
      KeyVaultName: 'envchec'
      SecretsFilter: '*'                          
      RunAsPreJob: false

  - script: |
      echo "secrets:" > $(System.DefaultWorkingDirectory)/my-chart/values.yaml
      echo "  keyVaultSecret1: $(AppName)" >> $(System.DefaultWorkingDirectory)/my-chart/values.yaml
      echo "  keyVaultSecret2: $(PortNumber)" >> $(System.DefaultWorkingDirectory)/my-chart/values.yaml
    displayName: 'Create values.yaml file'

  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'kubecluster'
      command: 'install'
      chartType: 'FilePath'
      chartPath: '$(System.DefaultWorkingDirectory)/my-chart'
      releaseName: 'env'
